DIV:	MOV A,D ;NEGATE THE DIVISOR
		CMA
		MOV D,A ; D HOLDS DİVİSOR
		MOV A,E
		CMA
		MOV E,A ;E HOLD REMAINDER
		INX D	;:FOR TWO'S COMPLEMENT
		LXI H,O ;IN ITIAL VALUE FOR REMAINDER
		MVI A,17 ;INITIALIZE LOOP COUNTER

DV0: 	PUSH H ;SAVE REMAINDER
		DAD D ;SUBTRACT DIVISOR (ADD NEGATIVE)
		JNC DVl ;UNDER FLOW, RESTORE HL
		XTHL
DV1:	POP H	
		PUSH PSW ; SAVE LOOP COUNTER (A)
		MOV A,C ;4 REGISTER LEFT SHIFT
		RAL		; WITH CARRY 
		MOV C,A ;;CY->C->B->L->H
		MOV A,B
		RAL
		MOV BA
		MOV A,L
		RAL
		MOV L,A
		MOV A,H
		RAL
		MOV H,A
		POP PSW ;RESTORE LOOP COUNTER (A)
		DCR A	;DECREMENT IT
		JNZ DVO ;KEEP LOOPING


;POST·DIVIDE CLEAN UP
;SHIFT REMAINDER RIGHT AND RETURN IN DE
		ORA A
		MOV A.H
		RAR
		MOV D,A ; D HOLDS DİVİSOR
		MOV A,L
		RAR
		MOV E,A ; E HOLD REMAINDER
		RET
		END